name: dockerloginDEVQA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  LogintodockerhubDEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{vars.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
    - name: Docker Build
      run: docker build -t github-actions-demo .
    - name: Docker Tag
      run: docker tag github-actions-demo neeharikarn9/github-actions-demo
    - name: Docker Push
      run: docker push neeharikarn9/github-actions-demo
